// API 型別改由 packages/shared-types 統一提供（前後端共用）
// 保留這個檔案讓既有的 `@/types/api` import 路徑不變
// 注意：必須用 export type（純型別 re-export，babel 才不會在 runtime 去 require 套件）
export type {
  ActivityType,
  AddFamilyMemberPayload,
  AiPlanDraft,
  AiPlanDraftActivity,
  AiPlanDraftDay,
  AiPlanPace,
  AiPlanPreferencesPayload,
  ApplyAiPlanActivity,
  ApplyAiPlanDay,
  ApplyAiPlanPayload,
  ApiResponse,
  Attraction,
  AttractionSearchResult,
  AuthResponse,
  CreateDayActivityPayload,
  CreateFamilyPayload,
  CreateFlightPayload,
  CreateHotelPayload,
  CreatePackingItemPayload,
  CreateTripDayPayload,
  CreateTripPayload,
  DayActivity,
  Family,
  FamilyMember,
  FamilyMemberWithUser,
  FamilyWithMembers,
  Flight,
  Hotel,
  PackingItem,
  Phrase,
  PhraseCategory,
  TripAttraction,
  TripDay,
  TripDetail,
  TripSummary,
  UpdateDayActivityPayload,
  UpdateFlightPayload,
  UpdateHotelPayload,
  UpdatePackingItemPayload,
  UpdateTripDayPayload,
  UpdateTripPayload,
  User,
} from '@travel-app/shared-types'
